# List of dependencies of the project

[versions]
kotlinx-serialization = "1.8.1"         # https://github.com/Kotlin/kotlinx.serialization/releases
ktor = "3.1.3"                          # https://ktor.io/docs/releases.html#release-details
prepared = "2.0.1"                      # https://opensavvy.gitlab.io/groundwork/prepared/docs/news/index.html

[plugins]

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }

prepared = { module = "dev.opensavvy.prepared:runner-kotest", version.ref = "prepared" }

[bundles]
